version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports: 
      - "8000:8000"
    environment:
      - HOST=true
      - NODE_ENV=production
      - PORT=8000
