version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    command: 
    - "--label-enable"
    - "--interval"
    - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=benjamin.pasco.78@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage:/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

  app:
    # container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    # image: myrepo/myimage:prod
    labels:
      - "traefik.http.routers.app.rule=HOST('benpas.eu')"
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    ports: 
      - "8000:8000"
    environment:
      - HOST=true
      - NODE_ENV=production
      - PORT=8000
    deploy:
      mode: replicated
      replicas: 3

volumes:
  letsencrypt: