version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    command: 
    - "--label-enable"
    - "--interval"
    - "30"
    - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=benjamin.pasco.78@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

  app:
    # container_name: app
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: bpasco/production:app
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=HOST(`benpas.eu`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - HOST=true
      - NODE_ENV=production
      - PORT=8000
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge

volumes:
  letsencrypt: